os:
    - linux
language: node_js
node_js:
    - 10
    - 'stable'
script:
    - yarn build
    - yarn test:coverage
notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/fcfc239ffee1c8d5a04a
        on_success: change
        on_failure: always
        on_start: never
